apiVersion: v1
kind: Secret
metadata:
  name: gangway-key
  namespace: auth-system
type: Opaque
data:
  sesssionkey: VUtvMC9hMk1zaWlkcTU1SmFsNXk3WmJqUExiVFFvalpDZFpYa2wyRHRmZz0=
---  
apiVersion: v1
kind: ConfigMap
metadata:
  name: gangway
  namespace: auth-system
data:
  gangway.yaml: |
    clusterName: "Kubernetes"
    apiServerURL: "https://kubernetes.default"
    authorizeURL: "https://auth.apps.k8s.cloudcafe.tech/auth"
    tokenURL: "https://auth.apps.k8s.cloudcafe.tech/token"
    clientID: "oidc-auth-client"
    clientSecret: "secret"
    redirectURL: "https://kubectl.apps.k8s.cloudcafe.tech/callback"
    scopes: ["openid", "profile", "email", "offline_access"]
    usernameClaim: "email"
    emailClaim: "email"
    # For insecure (selfsign), 509 certificate error
    trustedCAPath: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gangway
  name: gangway
  namespace: auth-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gangway
  template:
    metadata:
      labels:
        app: gangway
    spec:
      containers:
      - command:
        - gangway
        - -config
        - /gangway/gangway.yaml
        env:
        - name: GANGWAY_SESSION_SECURITY_KEY
          valueFrom:
            secretKeyRef:
              key: sesssionkey
              name: gangway-key
        #image: gcr.io/heptio-images/gangway:v2.0.0
        image: gcr.io/heptio-images/gangway:v3.2.0
        imagePullPolicy: Always
        name: gangway
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: certs
        - mountPath: /gangway/
          name: gangway
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 420
          name: gangway
        name: gangway
      - name: certs
        secret:
          defaultMode: 420
          secretName: gangway
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gangway
  name: gangway-svc
  namespace: auth-system
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: gangway
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gangway
  namespace: auth-system
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    #cert-manager.io/cluster-issuer: "private-ca"
    cert-manager.io/cluster-issuer: "selfsigned-issuer"    
spec:
  ingressClassName: nginx
  tls:
  - secretName: gangway
    hosts:
    - kubectl.apps.k8s.cloudcafe.tech
  rules:
  - host: kubectl.apps.k8s.cloudcafe.tech
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: gangway-svc
              port:
                number: 80
