apiVersion: v1
kind: ServiceAccount
metadata:
  name: console
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: console
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: console
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: console
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: console
type: kubernetes.io/service-account-token
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
  namespace: kube-system
  labels:
    app: console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
      - name: console-app
        # OCP K8s version map (https://gist.github.com/jeyaramashok/ebbd25f36338de4422fd584fea841c08)
        # Image (https://quay.io/repository/openshift/origin-console?tab=tags)
        # Till image (origin-console:4.11) Virtualizattion menu is available
        # Create Dex CA (kubectl create cm dex-cert --from-file=ssl/ca.crt -n kube-system)
        image: quay.io/openshift/origin-console:4.11
        env:
        - name: BRIDGE_K8S_MODE_OFF_CLUSTER_ENDPOINT
          value: https://kubernetes.default #master api
        - name: BRIDGE_K8S_MODE_OFF_CLUSTER_SKIP_VERIFY_TLS
          value: "true" # no tls enabled
        - name: BRIDGE_BASE_ADDRESS
          value: "http://console.34.100.203.210.nip.io" # Console URL
        - name: BRIDGE_K8S_AUTH
          value: oidc
        - name: BRIDGE_USER_AUTH
          value: oidc
        - name: BRIDGE_DEX_API_HOST
          value: "https://auth.34.100.203.210.nip.io"
        - name: BRIDGE_USER_AUTH_OIDC_ISSUER_URL
          value: "https://auth.34.100.203.210.nip.io/"
        - name: BRIDGE_USER_AUTH_OIDC_CLIENT_ID
          value: oidc-auth-client
        - name: BRIDGE_USER_AUTH_OIDC_CLIENT_SECRET
          value: secret
        - name: BRIDGE_USER_AUTH_OIDC_CA_FILE
          value: "/tmp/ca.crt"
        volumeMounts:
        - mountPath: /tmp/ca.crt
          name: dex-cert
          subPath: ca.crt
      volumes:
      - name: dex-cert
        configMap:
          defaultMode: 420
          name: dex-cert
---
kind: Service
apiVersion: v1
metadata:
  name: console
  namespace: kube-system
spec:
  selector:
    app: console
  type: NodePort
  ports:
  - name: http
    port: 9000
    targetPort: 9000
    nodePort: 30090
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: console-ingress
  namespace: kube-system
  annotations:
spec:
  ingressClassName: nginx
  rules:
  - host: console.34.100.203.210.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: console
            port:
              number: 9000
