apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio-store
  labels:
    app: minio
spec:
  clusterIP: None
  ports:
  - port: 9000
    name: minio
  selector:
    app: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: minio-store
spec:
  type: NodePort
  selector:
    app: minio
  ports:
  - name: minio-console
    protocol: TCP
    port: 9090
    targetPort: 9090
  - name: minio-api
    protocol: TCP
    port: 9000
    targetPort: 9000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: minio-store
  labels:
    app: minio
spec:
  serviceName: minio
  replicas: 2
  #replicas: 2  
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        args:
        - server   # who are our servers in cluster (below)
        - http://minio-0.minio.minio-store.svc.cluster.local/data
        - http://minio-1.minio.minio-store.svc.cluster.local/data
        #- http://minio-2.minio.minio-store.svc.cluster.local/data        
        - --console-address   # which port for console
        - :9090
        env:
        - name: MINIO_ROOT_USER
          value: "minioadmin"
        - name: MINIO_ROOT_PASSWORD
          value: "admin@2675"
        - name: MINIO_IDENTITY_OPENID_CONFIG_URL
          value: "https://auth.34.16.137.32.nip.io/.well-known/openid-configuration"
        - name: MINIO_IDENTITY_OPENID_CLIENT_ID
          value: "oidc-auth-client"
        - name: MINIO_IDENTITY_OPENID_CLIENT_SECRET
          value: "secret"
        - name: MINIO_IDENTITY_OPENID_REDIRECT_URI
          value: "https://minio-console.34.16.137.32.nip.io/oauth_callback"
        - name: MINIO_IDENTITY_OPENID_SCOPES
          value: "groups,openid,email,profile"
        - name: MINIO_IDENTITY_OPENID_CLAIM_NAME
          value: "groups"
        - name: MINIO_IDENTITY_OPENID_CLAIM_PREFIX
          value: ""
        - name: MINIO_IDENTITY_TLS_ENABLE
          value: "on"
        - name: MINIO_IDENTITY_TLS_SKIP_VERIFY
          value: "on"
        ports:
        - containerPort: 9000
          hostPort: 9000
        - containerPort: 9090
          hostPort: 9090
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /root/.minio/certs/CAs/ca.crt
          name: dex-cert
          subPath: ca.crt
      volumes:
      - name: dex-cert
        configMap:
          defaultMode: 420
          name: dex-cert
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: local-path
      resources:
        requests:
          storage: 5Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-console
  namespace: minio-store
  labels:
    app: minio
spec:
  tls:
  - secretName: minio
    hosts:
    - minio-console.34.16.137.32.nip.io
  ingressClassName: nginx
  rules:
  - host: minio-console.34.16.137.32.nip.io
    http:
      paths:
      - backend:
          service:
            name: minio-svc
            port:
              number: 9090
        path: /
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-api
  namespace: minio-store
  labels:
    app: minio
spec:
  ingressClassName: nginx
  rules:
  - host: minio-api.34.16.137.32.nip.io
    http:
      paths:
      - backend:
          service:
            name: minio-svc
            port:
              number: 9000
        path: /
        pathType: Prefix
